version: '3.6'

services:
  api:
    ports:
      - '1337:8080'
    environment:
      - GIN_MODE=debug
      - GOOD_RESOLUTIONS_API_PORT=8080
      - GOOD_RESOLUTIONS_API_GRAPHQL_PLAYGROUND_ENABLED=true
    restart: unless-stopped

  postgres:
    ports:
      - '5432:5432'
