version: '3.6'

services:
  # Backend
  api:
    image: docker.pkg.github.com/landazuripaul/good-resolutions/api:latest
    environment:
      - GOOD_RESOLUTIONS_API_HOST=0.0.0.0
      - GOOD_RESOLUTIONS_API_GRAPHQL_PATH=/graphql
      - GOOD_RESOLUTIONS_API_GRAPHQL_PLAYGROUND_PATH=/
