version: '3.6'

services:
  api:
    ports:
      - '8080:7777'
    environment:
      - GIN_MODE=debug
      - GOOD_RESOLUTIONS_API_PORT=7777
      - GOOD_RESOLUTIONS_API_GRAPHQL_PLAYGROUND_ENABLED=true
    restart: unless-stopped
